export * from "./hero"
export * from "./feel-like"
export * from "./faqs"
export * from "./how-to-enter"
export * from "./paradise"
export * from "./past-winners"
export * from "./subscriptions"
export * from "./what-is-winlads"